if [[ ! -d ~/.zplug ]]; then
    git clone https://github.com/zplug/zplug ~/.zplug
fi

source ~/.zplug/init.zsh

zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting"

zplug plugins/git, from:oh-my-zsh

zplug "jamiewilson/predawn-shell", as:theme
#zplug "eendroroy/alien-minimal", as:theme
#zplug "retroalgic/aplos", as:theme
#zplug "akz92/clean", as:theme
#zplug "potasiyam/cmder-zsh-theme", as:theme
#zplug "cusxio/delta-prompt", as:theme
#zplug "davydovanton/excess.zsh-theme", as:theme
#zplug "chauncey-garrett/zsh-prompt-garrett", as:theme
#zplug "nicolaracco/gawaine.zsh-theme", as:theme
#zplug "tylerreckart/hyperzsh", as:theme
#zplug "hevi9/infoline-zsh-theme", as:theme
#zplug "k-kinzal/oh-my-zsh-sinon-theme", as:theme

fpath+=~/.zfunc

zplug load

PROMPT_START_TAG='=> '
PROMPT_END_TAG=' $'
PROMPT_START_TAG_COLOR=81
PROMPT_END_TAG_COLOR=81

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

source $HOME/devel/dotfiles/zsh/zshrc-exports
source $HOME/devel/dotfiles/zsh/zshrc-aliases
